version: "3.3"

services:

  data_loader:
    build:
      context: .
      dockerfile: ./data_loader/DockerfileInsertData
      args:
        - OPENAI_API_KEY="${OPENAI_API_KEY}"
        - POSTGRES_DATABASE=${POSTGRES_DATABASE}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - EMBEDING_COLLECTION_NAME=${EMBEDING_COLLECTION_NAME}
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - POSTGRES_DATABASE=${POSTGRES_DATABASE}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - EMBEDING_COLLECTION_NAME=${EMBEDING_COLLECTION_NAME}
    depends_on:
      postgresql:
        condition: service_healthy

  inference:
    build:
      context: .
      dockerfile: ./inference/DockerfileCreateEndpoint
      args:
        - OPENAI_API_KEY=${OPENAI_API_KEY}
        - POSTGRES_DATABASE=${POSTGRES_DATABASE}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - EMBEDING_COLLECTION_NAME=${EMBEDING_COLLECTION_NAME}
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - POSTGRES_DATABASE=${POSTGRES_DATABASE}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - EMBEDING_COLLECTION_NAME=${EMBEDING_COLLECTION_NAME}
    depends_on:
      postgresql:
        condition: service_healthy
    ports:
      - "8000:8000" 

  postgresql:
    build:
      context: ./postgres
      dockerfile: DockerfilePostgresql
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5433:5432" 
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DATABASE}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s